import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'

const HealthID = ({ patientData, onHealthIDGenerated }) => {
  const navigate = useNavigate()
  const [healthID, setHealthID] = useState('')
  const [qrCodeData, setQRCodeData] = useState('')
  const [showQRCode, setShowQRCode] = useState(false)

  useEffect(() => {
    // Generate or load existing Health ID
    const existingID = localStorage.getItem('healthID')
    if (existingID) {
      setHealthID(existingID)
      generateQRCode(existingID)
    } else {
      generateNewHealthID()
    }
  }, [patientData])

  const generateNewHealthID = () => {
    // Generate unique Health ID (format: SH-YYYY-XXXXXXXX)
    const year = new Date().getFullYear()
    const randomNum = Math.random().toString(36).substr(2, 8).toUpperCase()
    const newHealthID = `SH-${year}-${randomNum}`
    
    setHealthID(newHealthID)
    localStorage.setItem('healthID', newHealthID)
    generateQRCode(newHealthID)
    onHealthIDGenerated?.(newHealthID)
  }

  const generateQRCode = (id) => {
    // Create QR code data with patient summary
    const qrData = {
      healthID: id,
      name: patientData?.name || 'Patient',
      age: patientData?.age || 'Unknown',
      bloodGroup: patientData?.bloodGroup || 'Unknown',
      emergencyContact: patientData?.emergencyContact || '',
      lastUpdated: new Date().toISOString(),
      medicalAlerts: patientData?.allergies || '',
      chronicConditions: patientData?.chronicDiseases || [],
      currentMedications: patientData?.currentMedications || '',
      generatedBy: 'SevaHealth AI',
      version: '1.0'
    }
    
    // In a real app, this would generate actual QR code
    // For demo, we'll create a data URL representation
    setQRCodeData(JSON.stringify(qrData, null, 2))
  }

  const shareHealthID = async () => {
    const shareData = {
      title: 'My SevaHealth ID',
      text: `My Health ID: ${healthID}\nGenerated by SevaHealth AI`,
      url: `${window.location.origin}/health-card?id=${healthID}`
    }

    if (navigator.share) {
      try {
        await navigator.share(shareData)
      } catch (err) {
        console.log('Error sharing:', err)
      }
    } else {
      // Fallback: copy to clipboard
      navigator.clipboard.writeText(`Health ID: ${healthID}`)
      alert('Health ID copied to clipboard!')
    }
  }

  const downloadQRCode = () => {
    // In a real app, this would generate and download actual QR code image
    const element = document.createElement('a')
    const file = new Blob([qrCodeData], { type: 'text/plain' })
    element.href = URL.createObjectURL(file)
    element.download = `SevaHealth-ID-${healthID}.txt`
    document.body.appendChild(element)
    element.click()
    document.body.removeChild(element)
  }

  return (
    <div className="bg-gradient-to-r from-blue-500 to-purple-500 rounded-xl p-6 text-white shadow-lg">
      {/* Health ID Card Header */}
      <div className="flex items-center justify-between mb-4">
        <div>
          <h2 className="text-xl font-bold">🆔 SevaHealth ID</h2>
          <p className="text-blue-100 text-sm">Digital Health Identity</p>
        </div>
        <div className="text-right">
          <div className="w-16 h-16 bg-white bg-opacity-20 rounded-full flex items-center justify-center">
            <span className="text-2xl">👤</span>
          </div>
        </div>
      </div>

      {/* Health ID Display */}
      <div className="bg-white bg-opacity-20 rounded-lg p-4 mb-4">
        <div className="text-center">
          <p className="text-blue-100 text-sm mb-1">Your Unique Health ID</p>
          <p className="text-2xl font-mono font-bold tracking-wider">{healthID}</p>
        </div>
      </div>

      {/* Patient Info Summary */}
      <div className="grid grid-cols-2 gap-4 mb-4 text-sm">
        <div>
          <p className="text-blue-100">Name</p>
          <p className="font-semibold">{patientData?.name || 'Not provided'}</p>
        </div>
        <div>
          <p className="text-blue-100">Age</p>
          <p className="font-semibold">{patientData?.age || 'Not provided'}</p>
        </div>
        <div>
          <p className="text-blue-100">Blood Group</p>
          <p className="font-semibold">{patientData?.bloodGroup || 'Not provided'}</p>
        </div>
        <div>
          <p className="text-blue-100">Last Updated</p>
          <p className="font-semibold">{new Date().toLocaleDateString()}</p>
        </div>
      </div>

      {/* Action Buttons */}
      <div className="grid grid-cols-2 gap-3">
        <button
          onClick={() => setShowQRCode(!showQRCode)}
          className="bg-white bg-opacity-20 hover:bg-opacity-30 py-3 rounded-lg font-medium transition-colors flex items-center justify-center gap-2"
        >
          <span>📱</span>
          {showQRCode ? 'Hide QR' : 'Show QR'}
        </button>
        
        <button
          onClick={shareHealthID}
          className="bg-white bg-opacity-20 hover:bg-opacity-30 py-3 rounded-lg font-medium transition-colors flex items-center justify-center gap-2"
        >
          <span>📤</span>
          Share ID
        </button>
      </div>

      {/* QR Code Display */}
      {showQRCode && (
        <div className="mt-4 bg-white rounded-lg p-4">
          <div className="text-center">
            <h3 className="text-gray-800 font-semibold mb-3">QR Code for Doctors</h3>
            
            {/* Mock QR Code - In real app, use QR code library */}
            <div className="w-48 h-48 mx-auto bg-gray-100 border-2 border-gray-300 rounded-lg flex items-center justify-center mb-3">
              <div className="text-center text-gray-600">
                <div className="text-4xl mb-2">📱</div>
                <p className="text-sm">QR Code</p>
                <p className="text-xs">{healthID}</p>
              </div>
            </div>
            
            <p className="text-gray-600 text-sm mb-3">
              Doctors can scan this QR code to access your health summary
            </p>
            
            <div className="flex gap-2 justify-center">
              <button
                onClick={downloadQRCode}
                className="bg-blue-500 text-white px-4 py-2 rounded-lg text-sm hover:bg-blue-600 transition-colors"
              >
                📥 Download
              </button>
              <button
                onClick={() => window.print()}
                className="bg-gray-500 text-white px-4 py-2 rounded-lg text-sm hover:bg-gray-600 transition-colors"
              >
                🖨️ Print
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Benefits Info */}
      <div className="mt-4 text-xs text-blue-100">
        <p className="mb-1">✓ Instant access to your health information</p>
        <p className="mb-1">✓ Works offline for emergency situations</p>
        <p>✓ Secure and encrypted data storage</p>
      </div>

      {/* Doctor Access Instructions */}
      <div className="mt-4 p-3 bg-white bg-opacity-10 rounded-lg">
        <h4 className="font-semibold text-sm mb-2 flex items-center gap-2">
          <span>👨‍⚕️</span>
          For Healthcare Providers
        </h4>
        <p className="text-xs text-blue-100">
          Scan the QR code or enter Health ID at sevahealth.ai/doctor to access patient summary, 
          AI analysis, and medical history with patient consent.
        </p>
      </div>
    </div>
  )
}

export default HealthID